---
title: 'STAT 231: Problem Set 7A'
author: "Majd Rouhana"
date: "due by 5 PM on Monday, October 26"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

In order to most effectively digest the textbook chapter readings -- and the  new R commands each presents -- series A homework assignments are designed to encourage you to read the textbook chapters actively and in line with the textbook's Prop Tip of page 33:

"\textbf{Pro Tip}: If you want to learn how to use a particular command, we highly recommend running the example code on your own" 

A more thorough reading and light practice of the textbook chapter prior to class allows us to dive quicker and deeper into the topics and commands during class.  Furthermore, learning a programming lanugage is like learning any other language -- practice, practice, practice is the key to fluency.  By having two assignments each week, I hope to encourage practice throughout the week.  A little coding each day will take you a long way!

*Series A assignments are intended to be completed individually.*  While most of our work in this class will be collaborative, it is important each individual completes the active readings.  The problems should be straightforward based on the textbook readings, but if you have any questions, feel free to ask me!

Steps to proceed:

\begin{enumerate}
\item In RStudio, go to File > Open Project, navigate to the folder with the course-content repo, select the course-content project (course-content.Rproj), and click "Open" 
\item Pull the course-content repo (e.g. using the blue-ish down arrow in the Git tab in upper right window)
\item Copy ps7A.Rmd from the course repo to your repo (see page 6 of the GitHub Classroom Guide for Stat231 if needed)
\item Close the course-content repo project in RStudio
\item Open YOUR repo project in RStudio
\item In the ps7A.Rmd file in YOUR repo, replace "YOUR NAME HERE" with your name
\item Add in your responses, committing and pushing to YOUR repo in appropriate places along the way
\item Run "Knit PDF" 
\item Upload the pdf to Gradescope.  Don't forget to select which of your pages are associated with each problem.  \textit{You will not get credit for work on unassigned pages (e.g., if you only selected the first page but your solution spans two pages, you would lose points for any part on the second page that the grader can't see).} 
\end{enumerate}

```{r, setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```


\newpage
# 1.  "Tell the truth. Don't steal. Don't harm innocent people."

In the textbook, the authors state, "Common sense is a good starting point for evaluating the ethics of a situation.  Tell the truth.  Don't steal.  Don't harm innocent people.  But, professional ethics also require a neutral, unemotional, and informed assessment."

(1a) Assuming the numbers reported in Figure 6.1 are correct (truthful), do you think Figure 6.1 is an *unethical* representation of the data presented?  Why or why not?

> ANSWER: I do think that Figure 6.1 is an unethical representation of the data presented. It is intentionally misleading in order to try and trick others into supporting an agenda. This is because the y-axis is flipped; thus, it appears that gun deaths decreased after the 'Stand Your Ground' law was passed, when in reality, it actually increased. By misleading by going against the standard convention, Figure 6.1 is intentionally spreading misinformation to support a political view; this is unethical, and the assessment is neither neutral nor unemotional.

(1b) Pulling from the examples in the textbook, provide one example of a more nuanced ethical situation (one that you perhaps found surprising or hadn't considered before).

> ANSWER: Vioxx is a drug that was pulled from the market in September 2004 due to evidence that the drug increases the risk of MI. Vioxx was approved in May 1999 by the FDA, but shortly after its approval it was found that Vioxx has a much higher rate of MI than a standard treatment. One could say that it's unethical that Vioxx wasn't withdrawn once this was found, and was only withdrawn when many people (88,000) had gotten heart attacks. However, the researchers had a theory that the higher rate of MI was due to "an aspect of the study protocol that excluded subjects who were being treated with aspirin to reduce the risk of heart attacks," and not Vioxx itself. These researchers were ultimately wrong. I find it interesting that people will always try to justify things to make it appear to fit the agenda they're trying to push. However, this does raise a question to me, are genuine mistakes as unethical as typical unethical situations? Overall, this situation is still unethical; professional standards must be applied in work, and can't be bended to fit an agenda or personal gain.

\newpage
# 2. Does publishing a flawed analysis raise ethical questions? 

In the course so far, we've touched upon some of the ethical considerations discussed in this chapter, including ethical acquisition of data (e.g., abiding by the scraping rules of a given website) and reproducibility.  At the end of Section 6.3.4 (the "Reproducible spreadsheet analysis" example), the authors ask: Does publishing a flawed analysis raise ethical questions?

After reading Section 6.4.1 ("Applying the precepts") for the "Reproducible spreadsheet analysis" example, re-consider that question: Does publishing a flawed analysis raise ethical questions?  And, a follow-up question for consideration: Does it depend on who published the flawed analysis (e.g., a trained data scientist? an economist who conducts data science work?  a psychologist who works with data? a clinician who dabbles in data science?)

In 4-6 sentences, respond to those questions and explain your response.   

> ANSWER: I think publishing a flawed analysis does raise ethical questions. Flaws could be done on purpose, or even done due to intentionally using an unreliable program (such as Excel in the example). Also, I think that before reporting an analysis of data to the public, the work must be double-checked to make sure that it is free of errors. Failing to do so means intentionally risking that the spread of misinformation, which is unethical itself. I think that publishing a flawed analysis could happen to anyone, but I think that the severity of how "unethical" it is does vary between those who publish the data. Someone who only dabbles in data science is much more likely to make mistakes or not know about the most reliable programs, so I think that mistakes can be forgiven more. Those very experienced, like a trained data scientist, are much more skilled and know to be more careful with their data analysis. While I think both professionals and novices to data science are being in unethical in publishing flawed analyses, I think that professionals in data science need to be held more accountable for being unethical.

